name = "user-conversation-worker"
main = "src/ai/index.js"
compatibility_date = "2023-10-01"

[ai]
binding = "AI"

# wrangler.toml (wrangler v3.79.0^)
[observability]
enabled = true
head_sampling_rate = 1